url = https://apeco-portal-qc.graycliff-e2cfdb11.eastus.azurecontainerapps.io/auth/login



chrome.driver=./src/main/resources/drivers/chromedriver.exe

username = apecouser@hotmail.com
password = P0rtal#Cqnyp

SchoolNameAr = 
SchoolNameEng = New Education School 31877


browser = firefox

AdminBrowser = firefox 
AdminPortalUrl = https://apeco-admin-portal-qc.graycliff-e2cfdb11.eastus.azurecontainerapps.io/login

employeeUsername = employee_01@hotmail.com
employeePassword= Adm1n#tro3eh

engineerUsername = Engineer_0001@hotmail.com
engineerPassword = Adm1n#tro3eh

reviewEmployeeUsername = Review_Employee@hotmail.com
reviewEmployeePassword = Adm1n#tro3eh

adminSchoolManagerUsername = schoolManager@apeco.com
adminSchoolManagerPassword = Adm1n#tro3eh

departmentManagerUsername = department_manager@hotmail.com
departmentManagerPassword= Adm1n#tro3eh